### ISSUE TITLE
Does this package use Measurement Protocol?

### ISSUE THREAD

**Issue by YodasMyDad** [Kolky/Allium#5]
Is this library built around this 

https://developers.google.com/analytics/devguides/collection/protocol/v1/devguide#ecom

If so, does it support eCommerce transactions?

**Comment by Kolky** [comment]
@YodasMyDad Not yet, but it could easily support it. It's a matter of adding the right [eCommerce](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#ecomm) parameters. Will probably pick it up soonish!

**Comment by Kolky** [comment]
Should be working from version [1.2.0](https://www.nuget.org/packages/Allium/1.2.0)! Except for most of the Enhanced E-Commerce features, that required more work and is something for later (#6).
